all:
	@echo "Compiling examples to verify the library"
	@(cd hara && make clean && make)
	@(cd hgemv && make clean && make)
	@(cd hcompress && make clean && make)
	@(cd hlru && make clean && make)
	@(cd horthog && make clean && make)
	@(cd tlr && make clean && make)
	@(cd fd && make clean && make)
	@(cd ns && make clean && make)
